### ISSUE TITLE
setup CI to publish charts

### ISSUE THREAD

**Issue by clkao** [InfuseAI/primehub#5]
## todos

- [x] create a repo to store Helm chart tarballs ([helm-chart](https://github.com/InfuseAI/helm-chart))
- [x] configure CI to publish charts 

## circle-ci

- [x] add ssh key to project
- [x] verfiy watched branches
- [x] update config.yml
- [x] update key path in script (or replace it to env-var)
- [x] review git author 

### branch to watch

https://github.com/InfuseAI/primehub/blob/0c0cc683a30e51d527361616b698bde6a623d352/.circleci/config.yml#L19-L21

### config.yml

https://github.com/InfuseAI/primehub/blob/0c0cc683a30e51d527361616b698bde6a623d352/.circleci/config.yml#L23-L26

### key path

https://github.com/InfuseAI/primehub/blob/0c0cc683a30e51d527361616b698bde6a623d352/ci/publish.sh#L9-L12

### review commit author

https://github.com/InfuseAI/primehub/blob/0c0cc683a30e51d527361616b698bde6a623d352/ci/common.sh#L60-L62

https://github.com/InfuseAI/helm-chart

## need to be confirmed

* which branch should ci to watch ? 
  * each changes in master
  * or use a release branch

**Comment by qrtt1** [comment]
will be done with #6
